### Predict the marks obtained based on the Number of hours studied and the number of hours slept

### 1.Import Pandas for data processing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

### 2.Read the CSV file

In [3]:
studet_data = pd.read_csv('02Students.csv')
studet_data

Hours  sHours  Marks
0       0       6     34
1       1       7     36
2       1       6     33
3       1       8     39
4       1       8     42
5       2       8     45
6       2       6     38
7       3       6     45
8       3       7     53
9       3       7     46
10      3       8     56
11      4       8     59
12      4       7     55
13      4       7     56
14      5       8     72
15      5       6     59
16      6       6     62
17      6       7     71
18      7       8     78
19      7       8     88
20      7       6     61
21      7       6     74
22      8       7     71
23      8       8     89
24      9       8     82
25      9       5     67
26      9       8     89
27     10       8     81
28     10       8     82
29     11       7     79

### 3.Split into X (Independent) and Y (predicted)

In [32]:
x = studet_data.iloc[:,: -1]
y = studet_data.iloc[:,2: 3]

In [30]:
#view X
x

Hours  sHours
0       0       6
1       1       7
2       1       6
3       1       8
4       1       8
5       2       8
6       2       6
7       3       6
8       3       7
9       3       7
10      3       8
11      4       8
12      4       7
13      4       7
14      5       8
15      5       6
16      6       6
17      6       7
18      7       8
19      7       8
20      7       6
21      7       6
22      8       7
23      8       8
24      9       8
25      9       5
26      9       8
27     10       8
28     10       8
29     11       7

In [33]:
#view Y
y

Marks
0      34
1      36
2      33
3      39
4      42
5      45
6      38
7      45
8      53
9      46
10     56
11     59
12     55
13     56
14     72
15     59
16     62
17     71
18     78
19     88
20     61
21     74
22     71
23     89
24     82
25     67
26     89
27     81
28     82
29     79

### 4.Split train and test data with 30% test size

In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 1234)

### 5.Train the Multiple Linear Regression

In [38]:
mlr_student_data = LinearRegression()
mlr_student_data

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### 6.Provide the training Data

In [39]:
mlr_student_data.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### 7.Predict the results

In [43]:
y_predict = mlr_student_data.predict(x_test)
y_predict

array([[45.76085662],
       [55.91055579],
       [46.57952582],
       [41.50467624],
       [88.56916066],
       [50.8357062 ],
       [46.57952582],
       [79.2381307 ],
       [65.24158575]])

### 8.Get the R-Squared

In [47]:
mlr_rscore = mlr_student_data.score(x_test, y_test)
mlr_rscore

0.9014449991870028

### 9.Coefficient and Intercept

In [49]:
mlr_coefficient = mlr_student_data.coef_
mlr_intercept = mlr_student_data.intercept_

In [50]:
#view mlr_coefficient 
mlr_coefficient

array([[4.66551498, 5.07484959]])

In [51]:
#view mlr_intercept 
mlr_intercept

array([1.31521415])

### 10.Calculate the errors using RMSE 

In [53]:
import math
mlr_rmse_student_sata = math.sqrt(mean_squared_error(y_test, y_predict))
mlr_rmse_student_sata

5.7553639416120195